"""empty message

Revision ID: 3706c27d9b65
Revises: aa38e5dc1548
Create Date: 2020-11-01 02:57:02.270611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3706c27d9b65'
down_revision = 'aa38e5dc1548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_keys',
    sa.Column('token', sa.String(length=120), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_keys')
    # ### end Alembic commands ###
