"""empty message

Revision ID: 74161199372b
Revises: c2239c8af265
Create Date: 2020-11-01 08:44:34.790597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74161199372b'
down_revision = 'c2239c8af265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debet_card_request', sa.Column('access_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debet_card_request', 'access_token')
    # ### end Alembic commands ###
